### ISSUE TITLE
Is it possible to filter by a value inside of list?

### ISSUE THREAD

**Issue by ondrowan** [dgraph-io/dgraph#2271]
I've found in docs that there's a list type and that you should be able to use functions on edges with this type, but there doesn't seem to be any mention how to use them. Is it even possible at this moment?

Eg. I have following nodes:

```
{ "name": "read-only", "permissions": ["read"] }
{ "name": "write-only", "permissions": ["write"] }
{ "name": "admin": "permissions": ["read", "write"] }
```

How would I query all nodes that have write permission?

**Comment by pawanrawal** [comment]
The same [functions](https://docs.dgraph.io/query-language/#functions) apply for list as well as non-list type. So considering that you have `permissions` indexed with a `hash`/`exact` tokenizer, you could do something like:

```
{
  me(func: eq(permissions, "write")) {
    name
    permissions
  }
}
```

**Comment by ondrowan** [comment]
I think there might be a bug when using `hash` index on list type. From what I've tried, the query from your post doesn't work unless I change the index to `exact`.

This is how I replicated it using version 1.0.4:

```
permissions: [string] @index(hash) .

{
  set {
    _:permission <permissions> "read" .
  }
}

{
  all(func: eq(permissions, "read")) {
    uid,
    expand(_all_)
	}
}
```

This doesn't return anything. When I do the same, but with `permissions: [string] @index(exact) .` as the first command, it works as expected.

**Comment by gpahal** [comment]
Should be fixed by https://github.com/dgraph-io/dgraph/pull/2317

**Comment by ondrowan** [comment]
I wanted to test it, but `master` Docker image of server keeps restarting with following error:

> unknown flag: --memory_mb

**Comment by gpahal** [comment]
`--memory_mb` has been renamed to `--lru_mb`

**Comment by ondrowan** [comment]
Ah damn, this PR isn't part of `master` docker image just yet anyway. Will try it when it's built again.

**Comment by ondrowan** [comment]
Using `hash` index on list type seems to be fixed, but regexp still doesn't work.
